name: Image Vault Upload

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Process upload issue
        run: |
          echo "Processing issue..."

          BODY='${{ github.event.issue.body }}'

          echo "$BODY" > payload.json

          FILENAME=$(jq -r '.filename' payload.json)
          CAPTION=$(jq -r '.caption' payload.json)
          IMAGE=$(jq -r '.image' payload.json)

          echo "$IMAGE" | base64 --decode > images/$FILENAME

          FILE="data.json"

          if [ ! -f "$FILE" ]; then
            echo "[]" > $FILE
          fi

          jq ". + [{
            file: \"images/$FILENAME\",
            caption: \"$CAPTION\"
          }]" $FILE > tmp.json

          mv tmp.json $FILE

      - name: Commit changes
        run: |
          git config user.name "image-vault-bot"
          git config user.email "bot@users.noreply.github.com"

          git add .
          git commit -m "upload image"
          git push

      - name: Close issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state":"closed"}'
